Add flaky hardware simulation job and pre-exit hook.

diff --git a/buildkite/pipeline.yml b/buildkite/pipeline.yml
--- a/buildkite/pipeline.yml
+++ b/buildkite/pipeline.yml
@@ -1,5 +1,6 @@
 steps:
-  - label: "Say hello"
+  - label: "Simulate flaky hardware"
     command: |
-      echo "Hello from the jobs"
-      buildkite-agent annotate "Job ran successfully" --style success --context job-result
+      echo "Running job..."
+      echo "ERROR: failed to register layer"
+      exit 1
