Add duplicate key to trigger 422 error

diff --git a/buildkite/pipeline.yml b/buildkite/pipeline.yml
--- a/buildkite/pipeline.yml
+++ b/buildkite/pipeline.yml
@@ -9,3 +9,14 @@ steps:
       automatic:
         - exit_status: "*"
           limit: 5
+
+  - label: "🔄 Another Flaky Test"
+    key: "simple-retry-pipeline"
+    command: |
+      echo "This step has the same key as the previous step"
+      echo "This will cause a 422 error"
+      exit 1
+    retry:
+      automatic:
+        - exit_status: "*"
+          limit: 3
