Restore pipeline after build skipping test

diff --git a/buildkite/pipeline.yml b/buildkite/pipeline.yml
--- a/buildkite/pipeline.yml
+++ b/buildkite/pipeline.yml
@@ -1,7 +1,10 @@
 steps:
-  - label: "Slow step"
-    key: "slow-step"
+  - label: "Pass step"
+    key: "pass-step"
+    command: echo "this passes"
+
+  - label: "Fail step"
+    key: "fail-step"
     command: |
-      echo "running for 30 seconds..."
-      sleep 30
-      echo "done"
+      echo "this will fail"
+      exit 1
